language: python
python:
    - 3.8
sudo: false

# safelist
branches:
    only:
    - master

addons:
  apt:
    packages:
      - software-properties-common  
      - libxml2-dev
      - zlib1g-dev
      - libcurl4-openssl-dev
      - wget
      - pandoc

cache:
    directories:
    - /usr/local/lib/R/site-library/

before_install:
    - sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/"
    - sudo apt-key adv --keyserver keys.gnupg.net --recv-key 'E298A3A825C0D65DFD57CBB651716619E084DAB9'
    - sudo apt-get update
    - sudo apt install --allow-unauthenticated r-base r-base-dev
    - pip3 --no-cache-dir install -r python-requirements.txt

install:
    - snakemake --cores 1 install_packages
    - snakemake --cores 1 install_rmd
    - snakemake --cores 1 install_tinytex
    - sudo chown -R `whoami`:admin /home/travis/.TinyTeX/

script:
    "snakemake --cores 1 all"